### ISSUE TITLE
缺少头文件

### ISSUE THREAD

**Issue by DyncEric** [Turing311/Realtime_AudioDenoise_EchoCancellation#1]
VS2017打开工程编译，报如下错误：
fatal error C1083: 无法打开包括文件: “tensorflow\lite\c\c_api.h”: No such file or directory

**Comment by DyncEric** [comment]
找到了

**Comment by Turing311** [comment]
I've fixed minor error.
I've recently tested about 8khz pcm direct input and commited by mistake.
Please check latest commit.

**Comment by Luzhiqiang20** [comment]
> VS2017打开工程编译，报如下错误：
> fatal error C1083: 无法打开包括文件: “tensorflow\lite\c\c_api.h”: No such file or directory
请问下， 这个应该怎么使用它在手机端

**Comment by Turing311** [comment]
Hi, Luzhiqiang20
Contact me at skype: ( live:turing311 )
