### ISSUE TITLE
和RNNoise有什么区别

### ISSUE THREAD

**Issue by DyncEric** [Turing311/Realtime_AudioDenoise_EchoCancellation#2]
如题 : )

**Comment by Turing311** [comment]
I've tried to find denoise and aec solution for my access control project.
It has mic and speaker together in the body, so audio feedback is major problem.
To manage it, I've used webrtc aecm and speex aec, but they didn't handle the problem well.
Webrtc aec3 worked good, but it was so heavy.
And rnndenoise had a great denoise effect, buf it couldn't distinguish feedbacked voice and not appropriate for AEC problem.
But though dtln is not designed for aec, but successfully seperate feedbacked voice as noise.
Hope any help for your project (AnyRTC).

**Comment by DyncEric** [comment]
Great, thks for reply,  i will test it in my project, 👍
